package com.idp.idp_platform.terraform.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents the result of a Terraform command execution.
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TerraformResult {

    /**
     * Indicates whether the command completed successfully.
     */
    private boolean success;

    /**
     * Terraform process exit code.
     * 0 = Success
     * Non-zero = Failure
     */
    private int exitCode;

    /**
     * Standard output generated by Terraform.
     */
    private String standardOutput;

    /**
     * Standard error generated by Terraform.
     */
    private String errorOutput;

    /**
     * Executed Terraform command.
     * Example:
     * terraform init
     * terraform validate
     * terraform plan
     */
    private String command;

    /**
     * Execution duration in milliseconds.
     */
    private long executionTime;
}